### ISSUE TITLE
Releases >1.1.0 are broken

### ISSUE THREAD

**Issue by carsonfarmer** [multiformats/js-cid#136]
It looks like the build assets are being nested in a "dist" folder upon npm publish. This appears to have been introduced in 0e11f035c9230e7f6d79c159ace9b80de88cb5eb? I _think_ the fix is to use a glob pattern here: https://github.com/multiformats/js-cid/commit/0e11f035c9230e7f6d79c159ace9b80de88cb5eb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R20 Or possibly fixing how the build folders are produced?

This mostly only affects typescript types, but relative path imports might also be affected?

**Comment by carsonfarmer** [comment]
cc @vmx and @Gozala

**Comment by carsonfarmer** [comment]
Note that as a "workaround" I have upgraded to https://github.com/multiformats/multiformats, which is working great :)

**Comment by vmx** [comment]
I think that was fixed with the 1.1.4 release. Please re-open/comment if I'm wrong.
