### ISSUE TITLE
Code not compiled to ES5

### ISSUE THREAD

**Issue by guoliu** [multiformats/js-cid#49]
The code published to npm is still in ES6 syntax (e.g. `Class` constructor in index file), instead of compiled to ES5. This is causing issue when building with `react-scripts`.

**Comment by vmx** [comment]
I guess that will be fixed with https://github.com/ipfs/aegir/issues/228

**Comment by vmx** [comment]
I think that's no longer an issue. Also the tooling has changes a lot since this issue was opened. Hence I'm closing this one.
