### ISSUE TITLE
Proposal: Moving CID to multiformats Org

### ISSUE THREAD

**Issue by daviddias** [multiformats/js-cid#67]
Please review https://github.com/ipld/cid/issues/26

**Comment by vmx** [comment]
@daviddias Please transfer this repo, I don't have enough permissions.

**Comment by vmx** [comment]
@daviddias Please give me push permission, best would be admin as I'm the lead maintainer.

**Comment by vmx** [comment]
@daviddias Thanks I can push now. Are there any reasons for not making me an admin?

**Comment by daviddias** [comment]
@vmx added you as an admin. Do note that these ad-hoc permissions are an opsec nightmare

**Comment by vmx** [comment]
Closed via https://github.com/multiformats/js-cid/pull/69.
