### ISSUE TITLE
Pulish latest changes to npm

### ISSUE THREAD

**Issue by pldespaigne** [multiformats/js-cid#85]
As requested [here](https://github.com/multiformats/js-multicodec/issues/42) could you publish latest changes to npm please ?

**Comment by vmx** [comment]
js-cid will have the latest changes once multicodec is released (as it will be a patch release) automatically, hence closing this issue (and leaving the js-multicodec on open).

**Comment by pldespaigne** [comment]
thx for the quick answer !
