### ISSUE TITLE
Bump version to 1.0

### ISSUE THREAD

**Issue by mikeal** [multiformats/js-cid#88]
We depend on this enough that I’d like some guarantees and practices around breaking changes. The first step is to push what is here as 1.0.

**Comment by achingbrain** [comment]
I think most of our modules should be v1 by now.

**Comment by vmx** [comment]
I think before a version 1.0 we should think about cleaning up the API. E.g. we could depracte `toBaseEncodedString()` and only have `toString()`.

Another things I'd like to see is https://github.com/multiformats/js-cid/pull/72, though this doesn't need (and probably shouldn't) be a breaking change anyway.

**Comment by vmx** [comment]
It is now at 1.0.0.
